# Generated by Django 5.2.2 on 2025-06-24 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('shipping', 'Shipping'), ('billing', 'Billing')], default='shipping', max_length=10, verbose_name='address type')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('company_name', models.CharField(blank=True, max_length=100, verbose_name='company name')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='tax ID')),
                ('street', models.CharField(max_length=200, verbose_name='street')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('postcode', models.CharField(max_length=20, verbose_name='postcode')),
                ('country', models.CharField(max_length=100, verbose_name='country')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'address',
                'verbose_name_plural': 'addresses',
                'ordering': ['-created_at'],
            },
        ),
    ]
