# Generated by Django 5.2.2 on 2025-06-24 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='newsletter_opt_in',
            field=models.BooleanField(default=False, verbose_name='newsletter opt-in'),
        ),
    ]
