# Generated by Django 5.2.2 on 2025-07-07 00:39

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_newsletter_opt_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vat_id', models.CharField(blank=True, help_text="Enter VAT ID if you're buying as a company.", max_length=15, validators=[accounts.models.validate_polish_nip], verbose_name='VAT ID (NIP)')),
                ('full_name_or_company', models.CharField(max_length=200, verbose_name='full name or company name')),
                ('street', models.CharField(max_length=200, verbose_name='street and number')),
                ('postal_code', models.CharField(help_text='Format: XX-XXX', max_length=6, validators=[accounts.models.validate_polish_postcode], verbose_name='postal code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_details', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'invoice details',
                'verbose_name_plural': 'invoice details',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('street', models.CharField(max_length=200, verbose_name='street and number')),
                ('postal_code', models.CharField(help_text='Format: XX-XXX', max_length=6, validators=[accounts.models.validate_polish_postcode], verbose_name='postal code')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('phone', models.CharField(help_text='Polish phone number', max_length=20, validators=[accounts.models.validate_polish_phone], verbose_name='phone number')),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'shipping address',
                'verbose_name_plural': 'shipping addresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
