# Generated by Django 5.2.2 on 2025-07-07 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_fix_vat_id_field_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicedetails',
            options={'ordering': ['-created_at'], 'verbose_name': 'invoice details', 'verbose_name_plural': 'invoice details'},
        ),
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'ordering': ['-created_at'], 'verbose_name': 'shipping address', 'verbose_name_plural': 'shipping addresses'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='invoicedetails',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='is_default',
        ),
    ]
