# Generated by Django 5.2.2 on 2025-06-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('is_dummy', models.BooleanField(default=False, help_text='Mark as dummy for easy removal', verbose_name='is dummy data')),
            ],
            options={
                'verbose_name': 'news item',
                'verbose_name_plural': 'news items',
                'ordering': ['-created_at'],
            },
        ),
    ]
