# Generated by Django 5.2.1 on 2025-07-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_barcode_product_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nutritional_info',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='nutritional information'),
        ),
    ]
