# Generated by Django 5.2.1 on 2025-07-20 23:17

from django.db import migrations


def migrate_legacy_images(apps, schema_editor):
    """Migrate legacy product images to ProductImage model"""
    Product = apps.get_model('shop', 'Product')
    ProductImage = apps.get_model('shop', 'ProductImage')
    
    # Get all products that have legacy images
    products_with_images = Product.objects.filter(image__isnull=False).exclude(image='')
    
    for product in products_with_images:
        # Create a ProductImage for the legacy image
        ProductImage.objects.create(
            product=product,
            image=product.image,
            alt_text=product.name,
            is_primary=True,  # Make the legacy image the primary image
            order=0
        )


def reverse_migrate_legacy_images(apps, schema_editor):
    """Reverse migration - this is not implemented as we're removing the field"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_product_nutritional_info'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_images, reverse_migrate_legacy_images),
    ]
