# Generated by Django 5.2.1 on 2025-07-20 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_migrate_legacy_images_to_product_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
